/*
 * Register Actions
 *
 */

import { POST_REGISTER_REQUESTING } from './constants';

export function registerUserAction({
  password,
  weight,
  height,
  phone,
  gender,
  name,
  age,
  nickname,
  imageBase,
  headOffset,
  footOffset,
  leftNeckOffset,
  leftShulderOffset,
  leftElbowOffset,
  leftHandOffset,
  rightNeckOffset,
  rightShulderOffset,
  rightElbowOffset,
  rightHandOffset,
  leftChestOffset,
  leftWaistOffset,
  leftPelvisOffset,
  rightChestOffset,
  rightWaistOffset,
  rightPelvisOffset,
  leftThighOffset,
  leftAnkleOffset,
  rightThighOffset,
  rightAnkleOffset,
}) {
  return {
    type: POST_REGISTER_REQUESTING,
    payload: {
      password,
      weight,
      height,
      gender,
      name,
      phone,
      age,
      nickname,
      imageBase,
      headOffset,
      footOffset,
      leftNeckOffset,
      leftShulderOffset,
      leftElbowOffset,
      leftHandOffset,
      rightNeckOffset,
      rightShulderOffset,
      rightElbowOffset,
      rightHandOffset,
      leftChestOffset,
      leftWaistOffset,
      leftPelvisOffset,
      rightChestOffset,
      rightWaistOffset,
      rightPelvisOffset,
      leftThighOffset,
      leftAnkleOffset,
      rightThighOffset,
      rightAnkleOffset,
    },
  };
}
