# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
pod 'Firebase/Core'
pod 'Firebase/Messaging', '~> 5.20.2'

target 'WaveRn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WaveRn
  target 'WaveRnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WaveRn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WaveRn-tvOS

  target 'WaveRn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
